name: Go Build

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  push: 
    branches: [ main ]
  

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: '1.24' # You can change this to your desired Go version

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          version: latest

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: golangci-lint run

      - name: Format Check
        run: |
          go fmt ./...
          if [ -n "$(git diff)" ]; then
            echo "Code is not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi

      - name: Test
        run: go test -v ./...